version: '3.3'
services:
  cassandra:
    container_name: scylla
    image: scylladb/scylla:2.2.0
    ports:
      - "9042:9042"
    command: "--developer-mode=1"
    volumes:
    - ./src/main/resources/scylla/schema.cql:/schema.cql
    #volumes:
     # - ./src/main/resources/scylla/data:/var/lib/scylla/data
     # - ./src/main/resources/scylla/commitlog:/var/lib/scylla/commitlog
  zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper:4.0.2
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:4.0.2
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #volumes:
     # - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper